### ISSUE TITLE
Dror Israel

### ISSUE THREAD

**Issue by doron-g** [doron-g/appCoronaDead#1]
need to add the logo + link to drorisarel site + add text to about.
you can pull all from dror_israel branch exept the logo

**Comment by amityizr** [comment]
i edited the text and set the flexbox better
![image](https://user-images.githubusercontent.com/20342245/101142967-f7d85200-361e-11eb-9ad4-838f8e4f2b6a.png)

no logo for now - because one color white logo needed and DI PR dont have one (yaaa, its wierd)

**Comment by doron-g** [comment]
Cant see dror Israel in mobile

**Comment by amityizr** [comment]
no need to see.. its in the ABOUT
it was to much to put it on mobile too
**do you think its importent?**

also - i recieved the white logo of DI - but it looks bad to add it...

**Comment by doron-g** [comment]
the problem is in the video i sent you yesterdy

**Comment by amityizr** [comment]
done
