### ISSUE TITLE
text goes over the popup

### ISSUE THREAD

**Issue by doron-g** [doron-g/appCoronaDead#3]
need to fix the text to the popup

**Comment by amityizr** [comment]
@doron-g , pls put some pic here
there are still stuff to fix, but its not what i think you meant 
i cant see it
![image](https://user-images.githubusercontent.com/20342245/101164473-bacf8800-363d-11eb-9dcd-2c261545e004.png)

**Comment by doron-g** [comment]
now its fine

**Comment by amityizr** [comment]
fixed in the grid of the card
mobile & desktop
